# Generated by Django 5.2.7 on 2025-10-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lng',
            new_name='lon',
        ),
    ]
