# Generated by Django 5.2.7 on 2025-10-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_lng_location_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['user_id'], name='reports_user_id_224fd3_idx'), models.Index(fields=['created_at'], name='reports_created_c5f642_idx'), models.Index(fields=['user_id', '-created_at'], name='reports_user_id_e58b58_idx')],
            },
        ),
    ]
