# Generated by Django 5.2.7 on 2025-10-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
