# Generated by Django 5.2.7 on 2025-10-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_report_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geohash', models.CharField(db_index=True, max_length=12)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_locations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='user_locati_user_id_03e796_idx'), models.Index(fields=['geohash'], name='user_locati_geohash_98af21_idx'), models.Index(fields=['user_id', 'is_active'], name='user_locati_user_id_5bfdd1_idx'), models.Index(fields=['created_at'], name='user_locati_created_d3d1bf_idx')],
            },
        ),
    ]
